(ns keywords-map)
(def lookup-maps
  [{:kw "__consuming" :def "" :use ""}
   {:kw "__owned" :def "" :use ""}
   {:kw "__setter_access" :def "" :use ""}
   {:kw "__shared" :def "" :use ""}
   {:kw "_backDeploy" :def "" :use ""}
   {:kw "_borrow" :def "" :use ""}
   {:kw "_borrowing" :def "" :use ""}
   {:kw "_BridgeObject" :def "" :use ""}
   {:kw "_Class" :def "" :use ""}
   {:kw "_compilerInitialized" :def "" :use ""}
   {:kw "_const" :def "" :use ""}
   {:kw "_consuming" :def "" :use ""}
   {:kw "_documentation" :def "" :use ""}
   {:kw "_dynamicReplacement" :def "" :use ""}
   {:kw "_effects" :def "" :use ""}
   {:kw "_forward" :def "" :use ""}
   {:kw "_implements" :def "" :use ""}
   {:kw "_linear" :def "" :use ""}
   {:kw "_local" :def "" :use ""}
   {:kw "_modify" :def "" :use ""}
   {:kw "_move" :def "" :use ""}
   {:kw "_mutating" :def "" :use ""}
   {:kw "_NativeClass" :def "" :use ""}
   {:kw "_NativeRefCountedObject" :def "" :use ""}
   {:kw "_noMetadata" :def "" :use ""}
   {:kw "_opaqueReturnTypeOf" :def "" :use ""}
   {:kw "_originallyDefinedIn" :def "" :use ""}
   {:kw "_PackageDescription" :def "" :use ""}
   {:kw "_read" :def "" :use ""}
   {:kw "_RefCountedObject" :def "" :use ""}
   {:kw "specialized" :def "" :use ""}
   {:kw "_specialize" :def "" :use ""}
   {:kw "_spi_available" :def "" :use ""}
   {:kw "_Trivial" :def "" :use ""}
   {:kw "_TrivialAtMost" :def "" :use ""}
   {:kw "_TrivialStride" :def "" :use ""}
   {:kw "_underlyingVersion" :def "" :use ""}
   {:kw "_UnknownLayout" :def "" :use ""}
   {:kw "_version" :def "" :use ""}
   {:kw "abi" :def "" :use ""}
   {:kw "accesses" :def "" :use ""}
   {:kw "actor" :def "" :use ""}
   {:kw "addressWithNativeOwner" :def "" :use ""}
   {:kw "addressWithOwner" :def "" :use ""}
   {:kw "any" :def "" :use ""}
   {:kw "Any" :def "" :use ""}
   {:kw "as" :def "" :use ""}
   {:kw "assignment" :def "" :use ""}
   {:kw "associatedtype" :def "" :use ""}
   {:kw "associativity" :def "" :use ""}
   {:kw "async" :def "" :use ""}
   {:kw "attached" :def "" :use ""}
   {:kw "autoclosure" :def "" :use ""}
   {:kw "availability" :def "" :use ""}
   {:kw "available" :def "" :use ""}
   {:kw "await" :def "" :use ""}
   {:kw "backDeployed" :def "" :use ""}
   {:kw "before" :def "" :use ""}
   {:kw "block" :def "" :use ""}
   {:kw "borrow" :def "" :use ""}
   {:kw "borrowing" :def "" :use ""}
   {:kw "break" :def "" :use ""}
   {:kw "canImport" :def "" :use ""}
   {:kw "" :def "" :use ""}
   {:kw "catch" :def "" :use ""}
   {:kw "class" :def "" :use ""}
   {:kw "compiler" :def "" :use ""}
   {:kw "consume" :def "" :use ""}
   {:kw "copy" :def "" :use ""}
   {:kw "consuming" :def "" :use ""}
   {:kw "continue" :def "" :use ""}
   {:kw "convenience" :def "" :use ""}
   {:kw "convention" :def "" :use ""}
   {:kw "default" :def "" :use ""}
   {:kw "defer" :def "" :use ""}
   {:kw "deinit" :def "" :use ""}
   {:kw "dependsOn" :def "" :use ""}
   {:kw "deprecated" :def "" :use ""}
   {:kw "derivative" :def "" :use ""}
   {:kw "didSet" :def "" :use ""}
   {:kw "differentiable" :def "" :use ""}
   {:kw "distributed" :def "" :use ""}
   {:kw "do" :def "" :use ""}
   {:kw "dynamic" :def "" :use ""}
   {:kw "each" :def "" :use ""}
   {:kw "else" :def "" :use ""}
   {:kw "enum" :def "" :use ""}
   {:kw "escaping" :def "" :use ""}
   {:kw "exported" :def "" :use ""}
   {:kw "extension" :def "" :use ""}
   {:kw "fallthrough" :def "" :use ""}
   {:kw "false" :def "" :use ""}
   {:kw "file" :def "" :use ""}
   {:kw "fileprivate" :def "" :use ""}
   {:kw "final" :def "" :use ""}
   {:kw "for" :def "" :use ""}
   {:kw "discard" :def "" :use ""}
   {:kw "forward" :def "" :use ""}
   {:kw "func" :def "" :use ""}
   {:kw "freestanding" :def "" :use ""}
   {:kw "get" :def "" :use ""}
   {:kw "guard" :def "" :use ""}
   {:kw "higherThan" :def "" :use ""}
   {:kw "if" :def "" :use ""}
   {:kw "import" :def "" :use ""}
   {:kw "in" :def "" :use ""}
   {:kw "indirect" :def "" :use ""}
   {:kw "infix" :def "" :use ""}
   {:kw "init" :def "" :use ""}
   {:kw "initializes" :def "" :use ""}
   {:kw "inout" :def "" :use ""}
   {:kw "internal" :def "" :use ""}
   {:kw "introduced" :def "" :use ""}
   {:kw "is" :def "" :use ""}
   {:kw "isolated" :def "" :use ""}
   {:kw "kind" :def "" :use ""}
   {:kw "lazy" :def "" :use ""}
   {:kw "left" :def "" :use ""}
   {:kw "let" :def "" :use ""}
   {:kw "line" :def "" :use ""}
   {:kw "linear" :def "" :use ""}
   {:kw "lowerThan" :def "" :use ""}
   {:kw "macro" :def "" :use ""}
   {:kw "message" :def "" :use ""}
   {:kw "metadata" :def "" :use ""}
   {:kw "modify" :def "" :use ""}
   {:kw "module" :def "" :use ""}
   {:kw "mutableAddressWithNativeOwner" :def "" :use ""}
   {:kw "mutableAddressWithOwner" :def "" :use ""}
   {:kw "mutating" :def "" :use ""}
   {:kw "nil" :def "" :use ""}
   {:kw "noasync" :def "" :use ""}
   {:kw "noDerivative" :def "" :use ""}
   {:kw "noescape" :def "" :use ""}
   {:kw "none" :def "" :use ""}
   {:kw "nonisolated" :def "" :use ""}
   {:kw "nonmutating" :def "" :use ""}
   {:kw "nonsending" :def "" :use ""}
   {:kw "objc" :def "" :use ""}
   {:kw "obsoleted" :def "" :use ""}
   {:kw "of" :def "" :use ""}
   {:kw "open" :def "" :use ""}
   {:kw "operator" :def "" :use ""}
   {:kw "optional" :def "" :use ""}
   {:kw "override" :def "" :use ""}
   {:kw "package" :def "" :use ""}
   {:kw "postfix" :def "" :use ""}
   {:kw "precedencegroup" :def "" :use ""}
   {:kw "preconcurrency" :def "" :use ""}
   {:kw "prefix" :def "" :use ""}
   {:kw "private" :def "" :use ""}
   {:kw "Protocol" :def "" :use ""}
   {:kw "protocol" :def "" :use ""}
   {:kw "public" :def "" :use ""}
   {:kw "read" :def "" :use ""}
   {:kw "reasync" :def "" :use ""}
   {:kw "renamed" :def "" :use ""}
   {:kw "repeat" :def "" :use ""}
   {:kw "required" :def "" :use ""}
   {:kw "rethrows" :def "" :use ""}
   {:kw "retroactive" :def "" :use ""}
   {:kw "return" :def "" :use ""}
   {:kw "reverse" :def "" :use ""}
   {:kw "right" :def "" :use ""}
   {:kw "safe" :def "" :use ""}
   {:kw "scoped" :def "" :use ""}
   {:kw "self" :def "" :use ""}
   {:kw "sending" :def "" :use ""}
   {:kw "Self" :def "" :use ""}
   {:kw "Sendable" :def "" :use ""}
   {:kw "set" :def "" :use ""}
   {:kw "some" :def "" :use ""}
   {:kw "spi" :def "" :use ""}
   {:kw "spiModule" :def "" :use ""}
   {:kw "static" :def "" :use ""}
   {:kw "struct" :def "" :use ""}
   {:kw "subscript" :def "" :use ""}
   {:kw "super" :def "" :use ""}
   {:kw "swift" :def "" :use ""}
   {:kw "switch" :def "" :use ""}
   {:kw "target" :def "" :use ""}
   {:kw "then" :def "" :use ""}
   {:kw "throw" :def "" :use ""}
   {:kw "throws" :def "" :use ""}
   {:kw "transpose" :def "" :use ""}
   {:kw "true" :def "" :use ""}
   {:kw "try" :def "" :use ""}
   {:kw "Type" :def "" :use ""}
   {:kw "typealias" :def "" :use ""}
   {:kw "unavailable" :def "" :use ""}
   {:kw "unchecked" :def "" :use ""}
   {:kw "unowned" :def "" :use ""}
   {:kw "unsafe" :def "" :use ""}
   {:kw "unsafeAddress" :def "" :use ""}
   {:kw "unsafeMutableAddress" :def "" :use ""}
   {:kw "using" :def "" :use ""}
   {:kw "var" :def "" :use ""}
   {:kw "visibility" :def "" :use ""}
   {:kw "weak" :def "" :use ""}
   {:kw "where" :def "" :use ""}
   {:kw "while" :def "" :use ""}
   {:kw "willSet" :def "" :use ""}
   {:kw "wrt" :def "" :use ""}
   {:kw "yield" :def "" :use ""}])